spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/retbot_bd
    username: postgres
    password: hx1232

  jpa:
    show-sql: true

logging:
  level:
    dev258.retbotbackend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "d3v-l0c4l-0nly-tr0c4-3st3-v4l0r-4ntes-de-pr0d-32chars+"